# Generated by Django 3.1.6 on 2021-04-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dole', '0002_auto_20210406_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact_no',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='purok_street',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
