# Generated by Django 3.1.6 on 2021-04-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dole', '0003_auto_20210406_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
