# Generated by Django 3.1.6 on 2021-04-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dole', '0004_auto_20210413_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact_no',
            field=models.CharField(blank=True, default='', max_length=11),
            preserve_default=False,
        ),
    ]
