# Generated by Django 3.1.6 on 2021-05-05 16:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_dole', '0007_sms_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='civil_status',
            field=models.CharField(choices=[('1', 'Single'), ('2', 'Married'), ('3', 'Widowed'), ('4', 'Separated'), ('5', 'Annulled'), ('10', 'None')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
